### ISSUE TITLE
Hierarchy metadata

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#103]
RA/RM>GeoObject types and Hierarchies Manager>Create a new hierarchy or edit an existing one

We need to associate some metadata to each hierarchy. Such metadata should include:

- Which institution created the hierarchy
- Start and End date: validity period for the hierarchy (this what will allow to identify which hierarchy was active for a particular date) => Now captured in ticket #434 
- Abstract describing what the hierarchy is about
- Progress
- access/use constraint => Now captured in ticket #435
- acknowledgment and disclaimer
- contact information

**Comment by SteeveEbener** [comment]
In addition to the above:

-  The window should have a title like "......hierarchy metadata"
- The field to capture the description should be bigger (see the one for the GeoObject types as a reference)

**Comment by SteeveEbener** [comment]
Implemented in version 0.7.0: The organization who created the hierarchy is now captured.

The rest remains to be implemented

**Comment by justinlewis** [comment]
Estimated with an 5 under the assumption that start and end date are just be basic date fields and not change over time settings to version the hierarchy.

**Comment by SteeveEbener** [comment]
These are meant to be the entry point for storing changes over time for a given hierarchy. See the examples I have posted in slack: https://commongeoregistry.slack.com/archives/C017M969FPD/p1599694288013600

**Comment by justinlewis** [comment]
On the partners call on Sep 23, 2020 it was agreed to try to implement the fields that don't need further discussion. Those needing more discussion that should not be implemented yet are:
- Start and End date: validity period for the hierarchy (this what will allow to identify which hierarchy was active for a particular date)
- access/use constraint

**Comment by SteeveEbener** [comment]
There might have been a misunderstanding.  The expected result is the same as the metadata profile implemented for the lists:
![image](https://user-images.githubusercontent.com/12602163/99795044-1857d500-2b66-11eb-923f-97cadf6d6692.png)

The access and use constraint information is not linked to the private/public issue.  These are fields that are captured for information purpose only => these field should be added as free text having no influence to any other elements in the CGR.

**Comment by justinlewis** [comment]
@steeveebener and I talked about this on December 2nd, 2020 and decided to rename "Description" to "Description (Abstract)"  in an effort to minimize confustion of the terminology. 

The remaining steps to resolve this ticket are:

- [ ] Rename "Description" to "Description (Abstract)" for hierarchies, Geo-Object types, and lists.
- [ ] Because the CGR displays optional and locale indicators in parenthesis (e.g. Description (optional) (defaultLocale) ) we need to distinguish between the label and these indicators. I suggest making the indicators (e.g. (optional) (defaultLocale) ) grey so visually they appear different.
- [ ] Remove "Acknowledgement and" from the "Acknowledgement and disclaimer" input to leave a single "Disclaimer" free form text input.
- [ ] Add an "Access Constraints" free text input field.
- [ ] Add a "Use Constraints" free text input field.
- [ ] Add a "Disclaimer" free text input field.
- [ ] Repace "Contact information" with "Contact name".
- [ ] Add a "Telephone number" as a free text input.
- [ ] Add an "Email address" as a free text input.
- [ ] Place Contact name, Telephone number, and Email address in a "Primary contact" sub-section of the modal.

See the screenshot in @steeveebener's message above for more info.

**Comment by SteeveEbener** [comment]
It should actually be as follow for the 3rd bullet point:  Remove "and disclaimer" from the "Acknowledgement and disclaimer" input to leave a single "Acknowledgement" free form text input.

The disclaimer part is captured in the 7th bullet

**Comment by SteeveEbener** [comment]
I have checked this ticket under ve 0.13.0 and all changes have been implemented => I am closing this ticket
