### ISSUE TITLE
Design UI/UX of the scheduled job page

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#111]
## User stories
1. As a Registry Administrator who uploaded some data I want to find the status of my upload and any issues that might have been detected.

When an upload occurs the data will be stored in a queue of scheduled jobs. These jobs will execute when the system allows. Once run the queue data for that job will be validated for final import.
1. If it passes validation it will be persisted to the system
2. If there are validation issues the issues will be registered for the user to address. 

In the case of #2 a UI/UX will be needed to present the records in the data that failed validation, why they failed validation, and a path to fixing the issues. Each issue (record) should be fixed one by one. When all the records are addressed the user must submit the changes all together. If more validation issues occur the problem resolution screen is used again to address the problems. This would continue until all the prblems are solved. However, in this case the user isn't able to solve all the issues they need a way to save some issues to be addressed later. 

TODO: determine if there is reusability overlap with:  https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/114

**General Requirements**
- [x] main page showing all the submitted jobs (e.g. data uploads)
- [x] job detail page showing all the information about a submitted job

## Conceptual sketches
- [Sketches](https://www.lucidchart.com/invitations/accept/1b296ca8-3660-455a-86bf-a3b1ee315233)

## Design mockups
- [Scheduled jobs design doc](https://docs.google.com/document/d/1PnEWeGrgsbBMB-TjBh3xsVtMkOVsecIik8Cf9UQutWo/edit?usp=sharing)

**Comment by aleecodes** [comment]
![Terraframe - jobs.png](https://images.zenhubusercontent.com/5e2ea77c92a0c84c88fa67b5/3f097e1b-4013-4ddd-b252-75e9ffcacd8b)

Here's a start of the jobs page

**Comment by nmceachen** [comment]
The link for the image seems to be broken

**Comment by nmceachen** [comment]
Each scheduled job will have the following properties:

- The type of job (they will need to be grouped), like Spreadsheet import, shapefile import, etc.
- Who executed the job (so that users will be able to see their jobs
- When the job started  
- The state of the job, such as a progress bar or “50 out of 500 processed”. This is a firm requirement.
- The status of the job (e.g. executing, completed). 

When completed the job  should say: "Completed successfully" or "Completed with errors". For these two outcomes, there should be a record import summary that says "1000 imported" or "900 imported, 100 have errors" respectfully.

Jobs that have completed with errors will have a link to the problem resolution screen so the user can fix those errors. The problem resolution screen can be discussed in another ticket.

**Comment by aleecodes** [comment]
![Terraframe - jobs – D2.png](https://images.zenhubusercontent.com/5e2ea77c92a0c84c88fa67b5/eed477c1-78df-4a26-9891-1f17451f528f)

**Comment by aleecodes** [comment]
![Terraframe - jobs – Review.png](https://images.zenhubusercontent.com/5e2ea77c92a0c84c88fa67b5/1ad4ebe7-eebd-4f3f-b733-6fbe9f9df74c)
