### ISSUE TITLE
Define and implement conflict types and resolutions for disparate list mapping

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#122]
1. Define the enumeration of conflicts recognized by the application (e.g. duplicate, missing value, unrecognized reference, etc.). 
2. Define possible resolution actions for each conflict scenario

**Comment by justinlewis** [comment]
Conflict Types:
1. RELATIONSHIP
2. DATATYPE
3. REQUIREDVALUE

**Comment by rrowlands** [comment]
1. RELATIONSHIP - Either a TermProblem or a LocationProblem thrown during validation, if the parent lookup algorithm is not code. If the parent lookup algorithm is code then it's net.geoprism.registry.io.ParentCodeException thrown as an ImportError.
2. REQUIREDVALUE - Most likely will be thrown as a com.runwaysdk.ProblemException as an ImportError. Might require some cleanup on the backend because the details about each attribute are concatenated onto the exception message. This is also true of most attribute validation problems.
3. SPATIALREFERENCE - Throws as an ImportError with type "net.geoprism.registry.io.InvalidGeometryException".
4. DUPLICATE - Throws as an ImportError with type "com.runwaysdk.dataaccess.DuplicateDataException".
