### ISSUE TITLE
Automatically create an [organization] RA role for organizations when created

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#123]
When an organization is created we must create a dedicated RA role for that organization.

**Comment by SteeveEbener** [comment]
The roles are not to be attached to a hierarchy but to a GeoObject type and this simply because:
1. Organization have the mandate over GeoObject Types and not hierarchies (eg. MOH in charge of health facilities
2. some hierarchies will be based on GeoObject types under the responsibility of different mandated agencies (eg: village under MOHA linked to a primary health care under MOH)

This is a very important point
