### ISSUE TITLE
DHIS2 Integration

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#13]
Design document: [Shared Google Doc](https://docs.google.com/document/d/1-jW953CL1UyxFHmko1SCRHNikbzdb1O9yvxZxXpVp_k/edit#)

Deprecated epic doc here (for reference):  [Shared Google Doc](https://docs.google.com/document/d/10VJP5U3kddULD0rPRzFu19gx88FeecEFXN_150qPbkY/edit#)

**Comment by dtreatman** [comment]
Clarification needed:

- Update this epic title to better differentiate from other DHIS2 epics

**Comment by steesdale** [comment]
** High-Level Description of what it is**
Terra Frame
- Sync hierarchies; populate DHIS2 with the hierarchy to get started 
- CGR is the master source of data and pushed for DHIS2
- Maybe want 

CHAI
- See something where you publish an update in CGR and it is in DHIS2; 
- See the app inside DHIS2 - quick navigation; View the hierarchy
- Less important to have DHIS2 pushing data into CGR 
- LAO; There are custom scripts that might get broken by leveraging the CGR

HGL
- CGR is pushing data into DHIS2 

** Goalpost is to improve consistency **

**Comment by steesdale** [comment]
**USER**
- Registry Contributor
- Developers of custom scripts (Laos) 
- DPC Admin User 
- A DHIS2 User
- CGR admin; 
- District Level Health Officer

**User Stories**
- As a district health officer, I want to use historic changes in DHIS2 (e.g., shapefiles or other types of geo-data) over time to view maps at different points of time, to compare trends for malaria.    

- As a district health officer, I want to view historic changes in DHIS2 (e.g., schema and map view) of types of geo-data over time to view changes over time, to interpret changes that happen to geo-data over time. 

- As a national surveillance officer or district health officer can view snapshots of hierarchy, geospatial information (points and polygons) and program data over time, to support the reporting and planning of malaria program. 

- As a district health officer, I want to make an update request for a change through DHIS2 interface, to suggest an update to a GeoObject, to help keep the list up to date.

- As a CGR admin, I want to invite a DHIS2 user to play a role in CGR, to help support its operations

- As a DHIS2 user, I want to use my same DHIS2 credentials, when I log in - so that I don't need multiple logins. 

- As a DHIS2 user, I want to have a read-only view, to see data from CGR. 

- As an admin, I want to control publishing updates and pushing updates into DHIS2, so that I make sure I am ready to make the geo-data change in DHIS2.  

- As a software developer, I want to ensure my custom scripts keep so that I don't need to re-code overthing

- As a DHIS2, I want to see, visualize, and download data that uses up to date data (sites/hierarchies) from the CGR 

- As a DHIS2 user, I want to review locations for planning purposes, to help support my program activities

- As a DHIS2 admin, I want to update my program hierarchy, so that

**Comment by steesdale** [comment]
Assumptions
- That DHIS2 will use the most recent published version of CGR data.  
- That HISP (local and global) has common goals and inventive + frameworks to integrate with CGR.

- That we can resolve semantic interoperability challenges between CGR and expectations from DHIS2 

- The RA + RM will use a CGR interface separate from DHIS2;  e.g., CGR.com

- That foci maybe a tracked entity

- That user 
Big Question
- if we are publishing a version,

**Comment by steesdale** [comment]
Cleaned up and consolidated all notes and comments into the linked google doc in the description.
