### ISSUE TITLE
Create ability to split, merge, and combine Geo-Objects

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#179]
TODO: attach this to specification.

There are times where a GeoObject needs to be split. When this happens the parent/child references need to be managed.

**Comment by SteeveEbener** [comment]
We need to be careful here.

While a split could also be applied to object types represented by points I will only focus my comment on those represented by polygons (contiguous or not):

1. The capture of the split does not have to start from a geometric perspective. Actually, most of the time this kind of changes, together with other historic change, will most likely first be triggered from the list and this simply because the new geometry for the concerned geographic objects does not exist (I would actually argue that it should ideally start by a change in the list before implementing such change in the geometry) 

2. The geometric editing should only be possible if the editing  capability has been enabled for the geoObject type in question and that the editing functionalities has been improved to include topology checks for the contiguous GeObject types

3. The information captured in the back should allow to rebuild the historic changes, meaning that we should be able to identify:
  - out of which GeoObject the new GeoObject resulting from the split has been created
  - That the GeoObject that has been split is not the same anymore from a geographic perspective.(Based on discussions with Nate in NY this one should already be addressed) 

4. The question of the codification of the new GeoObject needs to be addressed.

=> In conclusion, we should define the set of rules that apply to each type of change that can occur depending on the format of the geoObject type. As a start, I am sharing here again a document which lists the different type of changes that can occur with contiguous polygons (administrative divisions for example): https://www.dropbox.com/s/gikhnt3dtk7ug68/Update_SALB_codes_250609.pdf?dl=0

.

**Comment by justinlewis** [comment]
This ticket was created before the currently implemented split, merge, and combine was planned. This ticket should have been used for that effort. So at this point the intent of the ticket is complete and should be closed. If there's items in your comment that aren't already in another ticket we may want to pull it out into another ticket.

**Comment by SteeveEbener** [comment]
Thanks. We can then close it
