### ISSUE TITLE
Change page title from GeoPrism Registry to Common Geospatial Registry

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#182]
![Screenshot from 2020-04-16 21-38-03.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/62814bbb-38df-483d-a830-8ab2d604100d)

**Comment by SteeveEbener** [comment]
Unfortunately, the tile of this issue was misleading while its content is correct.

The tab in the browser should not read "Common Geospatial-Registry" but "Common Geo-Registry" or "CGR" as per the included screenshot

Many thanks in advance for adjusting this as this is the first thing you see when opening the CGR now and it is not correct

**Comment by justinlewis** [comment]
How about now?

![Screenshot from 2020-06-01 22-08-01.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/ae38589e-f244-46b6-ae6a-875e08cfc021)

**Comment by SteeveEbener** [comment]
That's the way I would expect it to appear but it still not like this on the staging instance.

![image](https://user-images.githubusercontent.com/12602163/83490052-eda79080-a4e1-11ea-8383-16e3f010ed64.png)

**Comment by SteeveEbener** [comment]
This has been implemented and can be closed
