### ISSUE TITLE
Representativity date (temporal validity), publication date and Organization not appearing in the metadata worksheet of an exported list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#213]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The representativity date (temporal validity), publication date and Organization are not appearing in the metadata worksheet of an exported list

**To Reproduce**
As a RA or RM:
1. Fill the metadata information in the metadata profile for a given list
2. Go to the list in question and refresh the view
3. Export the master list in a spreadsheet
4. Open the Metadata worksheet the spreadsheet that has been generated
3. See error: the fields in question are not filled

**Expected behavior (clear and concise)**
The fields in question are filled in the metadata worksheet

In addition to that:
- We should also change "Publish Date" by "Date Published" and "Representativity date" by "List valid for" to match the recent changes implemented in the lists module
- The full name of the organization should appear in the "Organization" field
- We should put the Data dictionary worksheet before the  Metadata one:
![image](https://user-images.githubusercontent.com/12602163/86558890-2a592280-bf8d-11ea-847a-5ac2ec364ee6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/80909443-ec583c00-8d5a-11ea-9362-af6f5a571e3e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
What is representativity date? That attribute is no longer filled out as part of the list metadata.  Should it be removed from the Excel export completely?

**Comment by SteeveEbener** [comment]
The temporal validity information is switched with the publication date as per the following example screenshot (List valid for 01.01.2000 published on 29.12.2020):

![image](https://user-images.githubusercontent.com/12602163/103255714-54802000-49c5-11eb-816d-f6be94c2e550.png)

=> this needs to be fixed

**Comment by SteeveEbener** [comment]
Tested in 0.13.2: the dates are in the right place now but the date format captured in the excel file is different from the one used in the platform (dd-mm-yy  while it should be mm-dd-yy)

**Comment by rrowlands** [comment]
We have done our best to format dates across the app in a localized way (i.e. a format specific to the currently selected localization for the end user's browser / locale toggle).

That being said I do think we need to agree on a format when it comes to import/exporting data, since it lives in a context outside of any single user's session and it will make our spreadsheets more portable. I would personally not have picked mm-dd-yy because I think this format will be confusing for international users. There is an international standard [which has gained a lot of traction](https://kirby.kevinson.org/blog/iso-8601-the-better-date-format/) in this space called [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), which is yyyy-mm-dd. I am a big advocate for ISO-8601, not just for this use-case, but for any import/export use-case.

**Comment by SteeveEbener** [comment]
@Richard. ISO 8601 is also what I was mentioning as an option in #225 => I am personally agreeing in using it not only for the import/export but across the whole platform to make it "ISO compliant" on this

**Comment by rrowlands** [comment]
A quick note about ISO-8061:

The full ISO-8601 standard writes time as such:
yyyy-MM-ddTHH:mm:ss.SSSZ

as an example:
1928-03-22T05:36:24.22Z

I am exporting the dates in this spreadsheet as:
2021-02-12

Where the date is written in UTC timezone, but since Excel as a format does not have any knowledge of time zones, this is something that will need to be documented somewhere since the dates in this spreadsheet will no longer match the dates displayed in the CGR (which are localized to the current user's timezone).

We do have the option here to follow true ISO-8601 format and write the date into excel as a string with a Z at the end which would make it very clear to the end user that we're using UTC time zone, however the downside is that it would no longer be taking advantage of Excel's built-in date type, and would instead just be a string. I made the decision here to use Excel's built-in date type because I thought it might make the export more useful, however if you think that true ISO-8601 is the superior choice here just let me know.

Finally, the system tracks hours, minutes and seconds for the publish date, however since we're not displaying any of that time information in the browser I decided to remove it from the spreadsheet as well. If you would prefer to have the time information just let me know.

**Comment by SteeveEbener** [comment]
=Hi @justinlewis. Thanks for your message and the complement of information regarding ISO 85=601. Very useful.

My feedback:
- Indeed no need to capture the hours, minutes and seconds
- No problem to have the date stored as a string in the metadata of the excel file 
- The timezone information would only be relevant for the "date published" as the date for "List valid for" is not machine generated, right? If this is the case then I don't think this information is important in this context. The only modules where this information might be useful is when capturing the day of an import or a change request

**Comment by rrowlands** [comment]
The "Valid For" date is generated by the server based upon the user selected "Publishing Start Date" and "Publishing frequency". When the server generates the master list versions it does so in UTC.

**Comment by SteeveEbener** [comment]
Tested under 0.14.0 and working. I am closing this ticket
