### ISSUE TITLE
End date attached to any attribute set to 12-31-5000 and format different from the start date

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#225]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The end date set for any attribute in a list is set to 12-31-5000 instead of the current date. This allows the user to extract lists in the future 

In addition to that, the “End date” (mm-dd-yyyy) is not captured in the same format as the start date (dd-mm-yyyy)

**To Reproduce**
As a RA/RM
1. Go to the list module
2. Open one of the list
3. Click the edit pen for one of the objects 
4. Click the edit button for one of the fields
5. See errors:
   - Start and end date not in the same format
   - End date set to 31st December 5000

**Expected behavior (clear and concise)**
1. Start and end are in the same format (something that should either be set by the SRA/RA or set by default to dd-mm-yyyy)
2. The end date for a given record is set to the current date (meaning it is adjusted each day that passes)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81487950-9e30c480-9295-11ea-8822-756b586ecf28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
I also just found out that the data format when submitting a change request is yyyy-mm-dd or  yyyy-dd-mm => another alignment to be performed

**Comment by justinlewis** [comment]
The first point @steeveebener brought up is not a bug but is a suggestion we should consider. The data '12-31-5000' means essentially infinity to the date input fields for browsers. So setting a single date would mean the value exists forever, or until more date/values are assigned. I think it would make sense to convert the display of that date to a label of "current". 

The second point is a bug and can be handled with a simple conversion if we decide to stay with showing a date rather than "current".

**Comment by justinlewis** [comment]
I addressed the items in Expected Behavior as follows:
1. The start date is an input field who's format is controlled by the browsers localization settings. So we can't control this. For the end date I standardized on yyyy-MM-dd format which better alighns with the web standards. So enddates should be consistent and align with start date if the browser settings use a localization that uses the yyyy-MM-dd format.
2. ....

**Comment by SteeveEbener** [comment]
If I understand correctly some user might end up with a start date format that is different from the end date one. That is going to be very confusing if this is the case => there is then really no way for all the dates in the system to be controlled by the browser localization settings? The objective of this ticket was for both date to appear in the same format (my localization is dd-mm-yyy for example).

**Comment by justinlewis** [comment]
I figured out a way. 

![Screenshot from 2020-12-17 21-04-36.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/455e3dfc-3bf3-4a09-a099-2bd50a8d1b12)

**Comment by SteeveEbener** [comment]
Cool :) Does that apply to the whole platform and free us from the browser specific localization?

**Comment by justinlewis** [comment]
I deletd my last comment because after testing I realized I jumped the gun. This is actually a hard problem to solve partially because of the new requirement to have the language toggle. There are ways to localize dates in the browser but to actually solve the problem of the input format aligning with the non-input date presentation is more difficult. To localize non-input text we need to explicitly tell the frontend what localization to use and have that specific date localization installed. This is typically done with a library like moment.js. By default they only have around 150 locales so any system that uses another locale would require a custom addition to this library. But the biggest issue is still that the input will use the language setting of the browser while the CGR language toggle may say to set the language to something else. We can detect the browser setting and we know what the toggle is set to but it is very possible that they do not align and we are left in the same position where the user is asking for conflicting date formats. We could always try to align with the browser setting since we can not change that but that might create confusion since the user toggled the language in the CGR. 

Another challenge we need to solve is to ensure alignment between the existing localization options and this date specific localization. They may not align so we need to ensure a mapping between the two and build the mechanism to work together. 

For any developer reading this a possible path is:
1. Create a mapping between the backend localization and this date localization. 
2. Utilize a date picker that is not the browser native input (e.g. https://www.npmjs.com/package/angular2-datetimepicker). This requires an intensive change around the entire app to ensure all date inputs are changed and that the style of the HTML aligns with other inputs.
2. Setup Moment.js to change localizations for the new date inputs based on what the CGR toggle is set to.

The goal of this approach is to separate the browsers native localization from how the CGR handles localization (e.g. the language toggle). 

Because of all this we have two options for this sprint:
1. Remove pull this out of the release to be worked on later.
2. Convert end date displays to disabled inputs that would utilize the browsers language setting consistently. This means that they may not respect the language toggle setting. 

Here's what this would look like on an English system:

![Screenshot from 2020-12-18 11-43-17.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/f9d15f3b-6a32-4948-86bc-8d9f708329a4)

**Comment by justinlewis** [comment]
I implemented option 2

**Comment by SteeveEbener** [comment]
The date is appearing in the same format (dd-mm-yyyy on my computer) across the windows I checked except in the new Geo-object type modal (yyyy-mm-dd) as per the following screenshot:

![image](https://user-images.githubusercontent.com/12602163/103252252-f3515000-49b6-11eb-8ce1-604f656d385f.png)

In addition to this, the RA/RM/RC can still extract an exploratory list in the future => I have created a new bug ticket for that (#500)

**Comment by justinlewis** [comment]
This took a lot of digging into browser and operating system specifications to find a reliable solution to show these labels as text vs disabled input fields but I figured it out. 


Here are what inputs look like with English(Australian) set:
![Screenshot from 2021-01-15 11-24-18.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/baa59ce7-039d-4b00-ae79-9d5d2b338af9)

Here are what text looks like with English(Australian) set:
![Screenshot from 2021-01-15 11-23-52.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/f9dad5f3-4333-4a44-b027-bcdddc09239b)

**Comment by justinlewis** [comment]
Reference Commit: https://github.com/terraframe/geoprism-registry/commit/bc2280ed7df13f58716098d44c838ead340f4583

**Comment by SteeveEbener** [comment]
Tested under 0.13.2 and here are the date format experienced across the platform on my side:
- Lists module
     - Exploratory section: Field to capture the date for which the list is extracted: dd-mm-yyyy
     - "List Valid For" and Date Generated": mm-dd-yyyy
     - When viewing a list: "Date Published" and "List Valid For" mm-dd-yyyy"
     - When editing an existing geo-object or adding a new one (instances): dd-mm-yyyy
- Change requests module:
     - Date contributed: dd-mm-yyyy
- Import module
     - Start date: dd-mm-yyyy 
- Scheduled Jobs module
     - started: mm-dd-yyyy
- Explorer
     - set date: dd-mm-yyyy
- Exported lists
     - "Date published" and "List valid for": dd-mm-yyyy
=> Still some alignment to be performed

**Comment by justinlewis** [comment]
Lists module
- [ ] Exploratory section: Field to capture the date for which the list is extracted: dd-mm-yyyy
- [ ] "List Valid For" and Date Generated": mm-dd-yyyy
- [ ] When viewing a list: "Date Published" and "List Valid For" mm-dd-yyyy"
- [ ] When editing an existing geo-object or adding a new one (instances): dd-mm-yyyy

Change requests module:
- [ ] Date contributed: dd-mm-yyyy

Import module
- [ ] Start date: dd-mm-yyyy

Scheduled Jobs module
- [ ] started: mm-dd-yyyy

Explorer
- [ ] set date: dd-mm-yyyy

Exported lists
- [ ]  "Date published" and "List valid for": dd-mm-yyyy

**Comment by SteeveEbener** [comment]
I was just made aware of ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601) who is promoting for the standardization of date using the YYYY-MM-DD format => shall we consider using this as the reference and implement this format in the CGR?

**Comment by justinlewis** [comment]
@steeveebener That standard is what we started with (comment on Dec 17 above) but this will not address the inconsistency fully between the HTML inputs and the text based display dates. Using that standard is a generally a good approach and we actually do but then translate before it's rendered on the display. However, we do have some options at the moment. See my last comment (I updated it).

**Comment by SteeveEbener** [comment]
@justinlewis. I can't seem to see the update you have done in your last comment.

The discussion about the use of this standard comes from the UN Geographic Information Section, not WHO. Based on this discussion ISO8106 is linked to ISO19115 for geospatial Metadata => this is the date format standard that will for example be implemented from now on in the SALB project.

**Comment by justinlewis** [comment]
@steeveebener There was no changes released since version 0.13.2 (the last version you tested on) which is why you can't see anything changed in the app. 

I talked with the CHAI implementation team and everyone agrees that using the ISO8106 standard would be the best approach given the current priorities. The longer term solution is to create a more custom date picker rather than using the HTML native date input.

**Comment by justinlewis** [comment]
I was asked to hold off on this until initial onboarding is finished in the current onboarding effort.

**Comment by SteeveEbener** [comment]
Tested under 0.14.6 and all the dates present the same format across the windows reported here. I am closing this ticket!
