### ISSUE TITLE
External systems configurations - back end

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#262]
See this document for additional context:

https://docs.google.com/document/d/1-jW953CL1UyxFHmko1SCRHNikbzdb1O9yvxZxXpVp_k/

The CGR will have an abstraction for representing external systems with which the CGR will integrate. This abstraction can be extended to add support for additional systems.

These classes will be defined as MdVertex classes, as instance data in the graph will need to reference them. The root abstract class will store the login credentials for the external system. Abstract methods will be implemented with the platform specific behavior, such as establishing a connection with a DHIS2 instance. A connect() method is listed in the UML class model above, but that is just a suggestion. The methods communicating with an external system will need to be defined and will most likely change through iterative development.

**Back end**
Define the External System class hierarchy as MdVertex classes. Define attributes listed in the UML diagram in metadata. Define abstract methods, such as connect, in the abstract class that would be applicable to all concrete implementations. Define these methods in the generated stub Java class and not in Runway metadata.

It needs to be discussed whether CRUD on External Systems would require a SRA role or an RA role.

**Comment by SteeveEbener** [comment]
Regarding  "It needs to be discussed whether CRUD on External Systems would require a SRA role or an RA role." do you mean the role that will give the authorization to sync with the CGR or the role that will be virtually attributed to the external system?

If the former, due to the fact that the SRA should not have the possibility to edit, delete or give access to organization specific data or information and that the  external system will access GeoObject types (and associated data) under the curation of a specific organization the  CRUD on external system should be defined at the RA level.

Regarding the latter, any external system should have an:

-  RC role when it comes to contributing data associated to GeoObject types **not** under the curation of the organization operating the external system
- RM role when it comes to contributing data associated to GeoObject type under the curation of the organization operating the external system

**Comment by nmceachen** [comment]
This is referring to registering external systems within the CGR. If the CGR is syncing with two instances of DHIS2, then two records will need to be defined. 

Regarding the configuration of synchronization tasks between instances of DHIS2 (using that platform as an example), then we need to discuss who has the authority to do so, as data managed in multiple hierarchies by different organizations will synchronize with the single DHIS2 hierarchy.
