### ISSUE TITLE
Support external IDs in the importer - front end

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#278]
Read this requirements doc for additional context:

https://docs.google.com/document/d/1-jW953CL1UyxFHmko1SCRHNikbzdb1O9yvxZxXpVp_k/

Implement support for associating an external ID from a given external system with a GeoObject. This will give the CGR the ability to export to and to synchronize with external systems. When importing data from an external system, we will need the ability to specify that, for a dataset, a column/attribute represents an external ID. The external ID would be stored as an attribute on a relationship between the GeoObject and the node representing the external system from which the data is from.

By importing a spreadsheet of health facilities that contains a column with the DHIS2 org unit ID, then this functionality can be used to establish a mapping between the objects in the CGR and the corresponding objects in DHIS2.

**Front End Work**

In the upload manager, there will be an additional label with the question “Are you importing this data from a system you want to synchronize with?” Only display this if one or more external systems have been configured. If the user selects yes, then give them a select list of external systems that have been defined.

Currently the user is prompted to match location references by name or by ID. This setting applies to all IDs in the dataset. This needs to be changed to give users the ability to specify the matching algorithm for each location attribute. Each location attribute will have the following options:

Match by code
Match by name
Match by external ID
TODO: If the importer is configured only for updates and not inserts and a given External_ID cannot be found, the user will be able to select a GeoObject to match. This will need to be elaborated on further regarding what this will entail.

**Comment by CarlyNel** [comment]
Hi @justinlewis. 

We're trying to understand what the blocker is on this ticket so that we can assist and help move things forward. It seems like there should be a mock up of the CGR user interface that allows the CGR user to specify the import strategy eg. Update only vs update and insert, as well as a UI that allows the CGR user to select existing GeoObjects to update for any imported records with an external ID that does not match a CGR GeoObject. 

Is our interpretation of this correct? Is there anything that we can do to assist?
