### ISSUE TITLE
SRA can give the SRA role to the RA of any organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#289]
**List the CGR information**
- CGR version: 0.7.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The SRA can give the SRA role to the RA of any organization

**To Reproduce**
As the SRA: 
1. Go to Setting 
2. Click on the editing pen for any user having the RA role
3. See error: the SRA can check the SRA box

**Expected behavior (clear and concise)**
There should only be one SRA and this role should be separated from an RA role => the check button should be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/84450859-00f5f100-ac84-11ea-8272-ef9c01665416.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Additional context (if any)**
Link to user role management and this case is not captured in the rights by role google spreadsheet => reason why I documented it here

**Comment by justinlewis** [comment]
The idea here is that an SRA can make anyone an SRA. Without this we wouldn't have a way to assign another user to be an SRA when setting up the CGR. We could counsider using the email mechanism but
1. that would be pretty strange behavior to only be able to add SRA's through email.
2. an SRA wouldn't be able to invite an existing user because of not allowing two users with the same email or username.

I think this is important to talk with the community about because assigning SRA roles to someone is important for:
1. Some use cases where shared SRA responsibilities are needed
2. Transitioning from one SRA to another. This could be tricky and will likely be handled differently by different groups.

**Comment by SteeveEbener** [comment]
Apart from the problem this poses from a conceptual perspective is the question of what will happen to the RA rights once he has been invited to become a SRA.

Because of the way we are currently describing rights in the google spreadsheet, and if I am not wrong, the RA should loose all is creating, editing and deleting rights

=> If ever a RA has to be nominated as a SRA this would have to be through a separated account in order for him to keep his function of RA for his organization
=> a SRA should not be able to convert a current RA into a SRA but should indeed invite him to create a new user account that would have this role.

I personally don't see any problem for the current SRA to invite an extra one via email but the fact that a different email would have to be used is an issue => this brings us back to one of our last discussion during which we discussed that uniqueness of account should be based on the username and not the email address

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.
