### ISSUE TITLE
SRA having editing right across all items (GeoObject types, hierarchies, lists,...) and all organizations

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#330]
**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The SRA has the editing rights over all the items (GeoObject types, hierarchies, lists,...) and across all the organizations in the CGR

**To Reproduce**
As a SRA: 
1. Go to any module and see the error: the SRA can edit any item across any organization

**Expected behavior (clear and concise)**
The SRA should only have the view right as per the content of the rights by role google spreadsheet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**
issue extracted from ticket #171

**Comment by SteeveEbener** [comment]
The SRA still has access to:

-  the edit pen in the Lists module. Even if the change can't be implemented (an error message appears when you click on the submit button) the SRA can fill all the fields available in this window. => Ticket #302 should be implemented 

- the Add GeoObject button. The same thing as what is happening for the edit pen button is being observed here

**Comment by justinlewis** [comment]
@steeveebener - I would like to close this ticket because
1. Ticket #302 addresses the edit button for SRA's viewing lists directly and we will get that ticket into the upcoming release. 
2. I created ticket [#400](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/400) for preventing SRA's from adding a GeoObject from the list and will get it into the upcoming release.

**Comment by SteeveEbener** [comment]
Hi @justinlewis . Sounds good. Closing this ticket.
