### ISSUE TITLE
Date Published does not update after publishing a list

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#332]
Logging on behalf of Derek

**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
After successfully publishing a list on the "Publishing" tab under the Master List Manager, the "Date Published" field does not update to reflect today's date.

**To Reproduce**
1. As an MOHA-RA go to the Master List Manager
2. Click the "View" button for the "Village Master List"
3. On the Published tab, hit the "Publish Lists" button and wait for it to show as complete.
4. See the error - the "Date published" date does not update.

**Expected behavior (clear and concise)**
I would expect that after successfully publishing a list, that the "Date Published" field would show today's date.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/622ea3aa-9bd7-44ca-bdde-f90a73ddca6e)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by CarlyNel** [comment]
Confirming that this still appears to be an issue: 

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/6a84b0c7-aff1-4ae5-8e1b-8c2fa3831f27)

**Comment by CarlyNel** [comment]
Just tested and this looks good to me. Screenshot below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/206c67d9-287a-4fae-b649-25e970f349e2)

**Comment by SteeveEbener** [comment]
@CarlyNel: This does actually not work if the list is private (staging instance). Example when logged in as the MOH RA for the Referral hospital master list (MOH)

=> this ticket needs to be re-opened

**Comment by CarlyNel** [comment]
Thanks for flagging this Steeve. I'll go ahead and reopen this ticket.

**Comment by jsmethie** [comment]
This works even with private lists.  I just ran it on staging on the Referral hospital master list. That being said there is the know bug which is fixed in 0.13 which prevents a list from publishing if it has a publish start date:

https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/484
https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/403
https://github.com/terraframe/geoprism-registry/issues/265 

If you want to retest this on staging then do it on a list which does not have a publish start date.
