### ISSUE TITLE
Change request form: Request for drop down arrow on Geo Object field 

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#341]
Instance: 
Staging - Firefox
0.8.1 on 26 June 2020

As an MOH-RM,

1. I wanted to submit a change request but it is currently not clear that the field for GeoObject needs to be chosen from a pre-loaded menu. 
2. I completed the form and tried to submit but nothing happened.
3. I realised afterwards in conversation with someone that the reason it didn’t submit is because I did not select a GeoObject from the predefined list which I didn’t realise existed at the time of submitting my change request.

I expected to see a drop down arrow in the GeoObject field (as is currently the case for the GeoObject Type field) telling me that I have to selected from a predefined list. 

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/2615d55f-02a4-43c5-8f6d-4851c4bb9db5)

**Comment by justinlewis** [comment]
The GeoObject field is is a search input (not dropdown) so maybe placeholder text would be the equivilent visual indicator?

I can't read the note in the screenshot so I might be missing something.

**Comment by CarlyNel** [comment]
Hi @justinlewis Thanks for checking in on this - Some kind of placeholder text in the field that indicates that there is a pre-defined list of GeoObjects to choose from would be great. I flagged this based on my limited and very first experience with creating GeoObjects. I think at the time I wrote "test" in the field, not understanding how it all worked, and no possible alternative search terms were shown. I went on to try and submit but obviously received an error.

**Comment by justinlewis** [comment]
Estimating for placeholder text.

**Comment by SteeveEbener** [comment]
The option of the text vs the need to modify how you select the GeoObject should be discussed because:
1. You need to know the name of the GeoObject to be able to find it
2. Most probably due to internet bandwidth issue, the platform can sometimes take quite some time to display the return of the search
3. The search seems to be some kind of case sensitive (I use "some kind of" because there is always one record containing the other case appearing in the list)
4. the list is incomplete (for example entering "a" in search for the Health Post GeoObject should return all the records as this character is included in "Health Post" 

Linked to the above, and also because in many countries you can have several GeoObject presenting the same name  for a given type (San Pedro, San Isidro, San Augustin,.... for example in the Philippines), , it would be important to also be able to search according to the unique ID and not only the name

=> this could almost be the topic for a design session

**Comment by justinlewis** [comment]
@SteeveEbener Displaying all the GeoObjects in a dropdown could result in a huge amound of data being sent to the browser. Some GeoObjectTypes could have 100s of thousands of locations. This also relates to #4 in your comment. The system shortens the response because returning all the GeoObjects with 'a' in them could be so large it could overload the browser or consume scarce internet bandwidth.

I'm not sure about #3. We'd have to verify if there is actually data with different casing in the system or if that is a very strange bug. That should be taken to a different ticket.

**Comment by SteeveEbener** [comment]
Thanks for the complement of information. This confirms even more the need to improve the user experience here.

Could we then please at least:

1. Allow the search to take place on the GeoObject unique ID or its name/label (is this component actually working across locales or only the default one)?  I foresee this as happening through two different fields, Searching on the ID would automatically provide the corresponding name/label. Searching on the name would automatically provide the corresponding unique ID. This would reduce the risk for the user to select the wrong GeoObject type. To illustrate my case:
![image](https://user-images.githubusercontent.com/12602163/89838658-62f8a700-db9e-11ea-958e-6350ed3c84c2.png)

2. "Force" the search capability to follow the structure of the information captured in the field. What I mean is that if the first character I enter is "a" I only get in the list options which starts with a and not also some that have "a" in the rest of the name. To illustrate my case:
![image](https://user-images.githubusercontent.com/12602163/89838822-c5ea3e00-db9e-11ea-84e5-c9dcd55c32a0.png)

3. To avoid for the search to be case sensitive. To illustrate my case (compare with the previous picture):
![image](https://user-images.githubusercontent.com/12602163/89838991-401ac280-db9f-11ea-853e-fa0981cfe140.png)

4. To increase the number of options appearing in the list. I think we could at least go until 10 if not 15.

Thanks in advance for your consideration on the above.

**Comment by CarlyNel** [comment]
Update on this ticket: (this ticket is linked to [#453](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/453))

I have just looked at this search function within the Explorer (since the submit functionality has been removed from the change request module). It's much better to how it was originally working.

There now appears to be consistency:
1) Searching in lower case or upper case returns the same results
2) The search function searches based on the first letter of the geo-object, and does not include geo-objects who have the searched-for letter in their name. 
3) I am able to search for the unique geo-object ID

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/3af15796-141e-4653-b46c-df9a57f98af5)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/aceb0835-34db-4eab-9386-962c05778bad)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/ff4fb826-f8b7-4591-abb4-6245a41a2829)

Side note: The search function also picks up geo-objects where part of the geo-object's name starts with the letter that's being searched for. Example below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/590ca4ad-b1bb-4624-9682-3ce7af8886a3)

@Steeve - Keen to hear your thoughts on the above as a lot of this was driven by your suggestions in earlier comments above.
Based on your feedback, we may be able to close this ticket.

image.png

**Comment by justinlewis** [comment]
Closing because the current behavior allows for searching on whole names without knowing exactly how the label starts.
