### ISSUE TITLE
Set of changes requests submitted by RC for a single GeoObject not completely captured and adding a separated "ticket" for a change not submitted by the RC

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#349]
**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
As a RC, I submitted the following change request for a single record in the Community health Workers GeoObject type from the lists module:
- Change of the name of the CHW from Hillary Avila to Steeve Ebener
- Added a new instance (version) of name for that same CHW starting from 01.01.2010 (from Steeve Ebener to Justin Lewis)
- Change the gender for this CHW from Female to Male over the whole 01.01.2000 to present period

As the RM in charge of this GeoObject type I got the following two "tickets" (see first screenshot below)
- the first one mentioning "Steeve Ebener" as the update (first screenshot) while the details refers to the second change (Justin Lewis) + the change in gender=> see second screenshot below
- the second one related to a change in parent while I did not submit any request of that kind

**To Reproduce**
As  the RC
1. Go to the list module
open the list for which you want to submit change the requests  under the mandate of your organization (CHW in this case)
2. Submit the changes described here above
3. log out

As the RM having the mandate over the GeoObject type
1. Go to the change request module
2. Open the request submitted by the RC (epnding)
3. See error described here above:
 - The content of the first ticket is confusing (no separation between the three changes that have been submitted'
 - The second ticket reports a change in parents while I did not submit any

**Expected behavior (clear and concise)**
1. Each change appears as a different "ticket" in the change request manager (3 separated tickets in the above mentioned case)
2. The platform does not create a ticket for a request that has not been submitted 

**Screenshots**

![image](https://user-images.githubusercontent.com/12602163/86070220-adbad580-baae-11ea-9869-72f755edb1ac.png)

![image](https://user-images.githubusercontent.com/12602163/86073165-d85c5c80-bab5-11ea-90a1-d19b88454d17.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**
Relates to the overall functionalities  and user interface/experience of the request manager and the possibility to submit request from the lists module

**Comment by justinlewis** [comment]
The second issue in this ticket:
> The second ticket reports a change in parents while I did not submit any

Should be fixed with Release version 0.11.1

**Comment by CarlyNel** [comment]
TF: The part where multiple changes are not separated into individual tickets is by design. This was done for simplicity of administration and implementation. This allows an admin to edit the values of a change request using the same GeoObject editor widget that’s used in other parts of the app. This should be a familiar interface that gives the admin the flexibility to change anything for that object they need at the time of moderation. 

CHAI: If multiple requests come through in one ticket, isn’t it all or nothing accept for the RA? And how would they handle accepting some change but not others (which can be common because of approvals needed to change boundaries but perhaps not contact info)? 

TF: The admin can change any of the changed items but ultimately the system is relying on users using the system in the way that makes the most sense for their team. This may mean submitting multiple requests for the same GeoObject. It’s worth noting that to support mobile we built an ability to submit multiple task per request however for the web-app implementation we did not break out a request into multiple tasks because of complexity. This could be done but I’m not sure right now what the estimate would be.

CHAI: Is a workaround that an RC can just submit tickets 1 by 1 to avoid what I noted above? And if so, would implementing #86 help to force them to just manually submit different changes for different types of changes? 

TF: Yes re workaround and yes a refined UX could help manage requests and user expectations better. Ultimately we would also need to make some backend changes to split those requests up. The assumption everyone made who approved this design in the past was that the users would know the data and would rather have an interface where the can set the new “state” of the object all at once rather than going through a bunch of requests.

**Comment by SteeveEbener** [comment]
Two things need to be separated here:
1. The interface used by the RC to submit a request
2. How the change requests are being accessed by the RM for validation

While I can see the value for the RC to have the possibility to include several changes linked to a specific GeoObject in a single form/window (as it is currently the case), these requests should appear as individual tickets on the side of the RA/RM at the time of validating them.

Apart from that, I would like to re-iterate that the RM SHOULD NOT be able to edit a request that has been submitted by a RC contrary to what is currently possible (See ticket #368).

**Comment by justinlewis** [comment]
@SteeveEbener I believe this ticket could be closed after the recent changes to the change requests and editing behavior?

**Comment by SteeveEbener** [comment]
@justinlewis . Good catch. Closing it
