### ISSUE TITLE
Missing the field to capture the organization to which the SRA is attached to

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#375]
When registering as well as once in the CGR, the SRA can't specify to which organization (real organization, not a CGR organization. Example: Ministry of Home Affairs) he is attached to because this field is not available

=> this field should be added

**Comment by justinlewis** [comment]
To clarrify, this is just a free form text field in which someone can add the value they want.  This will have no effect on the roles behaviors for CGR Organization.

**Comment by SteeveEbener** [comment]
Yes, this is correct (free text)

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.

This has been added to the System Admin ticket to replicate the need for that role.
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/480

**Comment by SteeveEbener** [comment]
This ticket still applies to the system admin role => captured as feedback 77 in the google spreadsheet
