### ISSUE TITLE
Bug: Published list available for a date in the future

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#404]
**List the CGR information**
- CGR version: 0.10.0
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
Publishing the lists for a given geographic object type create an instance of the list of a date in the future (December 31, 2020)

**To Reproduce**
As a RA/RM:
1. Go to the lists module
2. Click the view button for a list on which the RA/RM has the  curation mandate and which presents an annual publishing frequency  (or a list under the curation of another organization for which all the instances have been published on an annual basis)
3. Publish the lists if not already done
4. See the error: a list is published for December 31, 2020 (see screenshot below)

**Expected behavior (clear and concise)**
The lists are only published until the present and not in the future

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/90487287-d7b67d00-e16c-11ea-9cc9-8eb8cfe2c0c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.125 (Official Build) (64-bit)

**Additional context (if any)**
Might be linked to the issue reported in ticket #225

**Comment by justinlewis** [comment]
This list is generated because there is valid data for at least one day in 2020. I realize it may not be a complete list because people may not have updated the data for the current year yet however it still could be considered valid because there is at least some data for the current year. This functionality should be validated by users.

**Comment by SteeveEbener** [comment]
Then there is an important misunderstanding at the conceptual level.

When you generate a list for a given date it is not meant to be representative of a year but of the date in question (the header of the column says "List valid for" and the information reported in this column is a date and not a year, which is how it should be). 

=> You can't have a list valid for 31 December 2020 while we are still in August 2020.
=> This is a but and it needs to be fixed

**Comment by CarlyNel** [comment]
Justin: Restricting future dates on both the backend and frontend would be about a 5 (story points). Right now the last (most recent) entry end date is always set to "infinity" so that there are no gaps. End dates can't be controlled directly because they're automatically snapped to the next start date, again to prevent gaps. Restricting future dates would mean if you are adding a new entry you couldn't set a start date to anything beyond the current day. In that case the last entry in change over time would be the current day to infinity. Infinity essentially just means the data is the last known value to current. So there is a concept of the future that would still exist but the lists can be restricted to the date of publish.

**Comment by CarlyNel** [comment]
This ticket is linked to additional tickets related to the validity period. Namely tickets [#388](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/388), [#424](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/424) and [#434](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/434). Steeve, please feel free to add any additional tickets that I may have missed.

**Comment by SteeveEbener** [comment]
We are starting to mix issues here. The original ticket is only about the fact that the lists module is publishing lists beyond the current day (in the future).

=> Justin's comment should be captured in a separated new ticket dealing with the limitations when defining  start dates across the platform. Ticket #424, and potentially #434,  should be attached to this new ticket. 

According to me, ticket #388  is not related to the topics discussed here.

**Comment by justinlewis** [comment]
What Carly posted above (quoted from me) was an explanation of how the underlying change over time is modeled as part of a conversation on what could be done for this situation. It's relevant to have that text here because it articulates that the data exists beyond the date of publish. For this ticket we will terminate the current year list date (e.g. end date of the list) to be the date of publish.

The other tickets linked are just for reference and won't impact this solution unless support for end dates across the whole system is supported before this ticket is worked on.

**Comment by SteeveEbener** [comment]
Being able to set a start date in the future, while this should not be possible, needs to be captured in a separated ticket in case this would still be possible after addressing the present ticket.

Just to make sure, by "For this ticket we will terminate the current year list date (e.g. end date of the list) to be the date of publish" do you mean that if I have set the publishing frequency to be annual, the frequency start date to be November 15th and I publish the lists today (September 30, 2020), the validity date of the last published list will be?:
1. November 15th, 2019
2. November 15th, 2020
3. September 30th, 2020

**Comment by justinlewis** [comment]
It would be #3 (September 30th, 2020).

**Comment by SteeveEbener** [comment]
This is not correct then according to me as the purpose of the frequency is only to publish the list for a specific date and this to allow for the organization to work on improving the content in between each publishing.

=> The correct answer should be November 15th, 2019 and there should not be any list published for 2020 until reaching November 15th, 2020.

**Comment by justinlewis** [comment]
Removing from Sprint 13 because there's a need to validate possible limitations of integration. This will be discussed in an upcoming design collaboration call.

**Comment by SteeveEbener** [comment]
@justinlewis : is it indeed now confirmed that this issue will be addressed with the new design change?

**Comment by justinlewis** [comment]
@SteeveEbener I think this is less of a concern with the new design. Right now you would get a List for the period that overlaps with the date published. This is NOT what you are recommending further up these comments. However, the visibility of the version snapshots are controlled for each snapshot. This means that no one outside the org needs to see a version of that time period until they decide to make them public. I'm basing this response on your statement above:

`this to allow for the organization to work on improving the content in between each publishing.`

**Comment by SteeveEbener** [comment]
@justinlewis . Once again, the instance generated using what we currently refer to as an "incremental series" are not representative of a period but of a specific date.

In addition to that, the instances in question are still valid for the day before the "publishing start date" specified when create the set (see ticket #265).

The above two things have to be adjusted before being able to identify if the issue reported in this ticket has been solved. Thanks

**Comment by SteeveEbener** [comment]
Tested under 0.18.1 and can't check if the issue has been solved as the each is still not stamped with a date but withy a year as per the following screenshot:
![image.png](https://images.zenhubusercontent.com/5e0a91f05164badb1470b68d/69a3b39b-159b-4b6f-b493-eabfc47a234a)

**Comment by rfromthecastle** [comment]
Experiencing an opposite issue in v0.19.3 (see #786), where now I only see lists generated until the end of 2021.

**Comment by SteeveEbener** [comment]
This ticket refers to the module before it has been upgraded to the new design. Rica's bug as well as other linked to the new module have been captured in other tickets => I am closing this one
