### ISSUE TITLE
Can't import the geometry contained in a shape file if the "Enable geometry editing" option is not checked

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#440]
**List the CGR information**
- CGR version: 0.11.1
- CGR instance (e.g. a URL): Demo and production

**Describe the bug (clear and concise)**
The geometry attached to a specific polygon format GeoObject type isn't imported from a shape file if the  "Enable geometry editing" option is not checked for that GeoObject type.

**To Reproduce**
As a RA/RM:
1. Go to the GeoObject type & Hierarchies module
2. Open the metadata window for one of the polygon format GeoObject type under the RA/RM curation mandate and for which you have a shape file
3. Uncheck the "GeoObject Editing" option if not already done
4. Go to the import module
5. Import the shape file in the graph
6. Go to the list module
7. Open (or create) the list for the GeoObject type in question
8. View the geometry of some of the GeoObject
9. See error: there is no geometry available (the Geometry window is not even accessible)

**Expected behavior (clear and concise)**
Importing a shape file is independent from editing it => You can import without needing for the Geometry editing option to be checked

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context (if any)**
None

**Comment by rrowlands** [comment]
As far as I can tell the importer is indeed importing the geometries in this scenario. You can see this if you click "edit" on the Geo-Object on a masterlist, it should render the geometries on the map:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/0528875e-6255-4d56-8e94-ee1b088bdc11)

This is what happened when I created a new Geo-Object with the Shapefile importer. You will notice that there is no way to edit the geometries (there is no attribute on the left), however that is because the geometry editing was disabled for the Geo-Object Type. If the checkbox is re-enabled that attribute should re-appear.

**Comment by SteeveEbener** [comment]
I wanted to test this under 0.15.4 but the "enable geometry editing" function is not working correctly (see ticket #667) => the test will have to be redone once this bug has been fixed.

This being said, I agree that the RA/RM/RC should still be able to edit/submit the geometry attributes (start and end date or add a new instance)

**Comment by SteeveEbener** [comment]
Tested under 0.19.5 and working. Closing this ticket
