### ISSUE TITLE
List Exploration: Filter options

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#450]
From Rica: "_When clicking inside the input text box that appears after clicking the filter button, for some attributes we see a list of options, but for some this doesn’t show_."

Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915).

**Comment by justinlewis** [comment]
This could be because of internet latency. We can try to reproduce this but if we aren't able to we'll need to know what list, browser, and steps where taken.

Either way the search could benefit from an indicator saying a search is in progress and if no results where found. There is [a ticket for this in Sprint 0.13.0.](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/463)

**Comment by jsmethie** [comment]
It also depends on the attribute type, we don't show options for normal text fields, date fields, and number fields

**Comment by jsmethie** [comment]
As a better indicator of which attributes are auto lookup vs which are not, we will add a placeholder to the input field which says 'Search...'
