### ISSUE TITLE
Geometry type not appearing anymore for  Geo-Object types represented by points

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#487]
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The Geometry type field is empty when looking at the metadata of a Geo-Object type represented by points and this independently from the organization under which the Geo-Object type is placed (see screenshot below).

This error does nevertheless not happen when you create a new Geo-Object type

**To Reproduce**
As a RA/RM/RC
1 Go to the Geo-Object types and Hierarchies module 
2. Click on the view or edit button of any Geo-Object type represented by points
3. See error in the Geometry type field 

**Expected behavior (clear and concise)**
The geometry type field is not empty when looking or editing the metadata attached to a geo-object type

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/101269059-592a2d80-37a5-11eb-87de-6b6d77165d91.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
I am not sure this is a valid bug.  The problem is that this Village Geo Object Type was created on a much older version of the software when the user could pick between POINT and MULTIPOINT for geometry.  However, the powers that be decided it was too complicated to have both options, so the POINT geometry type was dropped and the label MULTIPOINT was changed to POINT.  This old Village Geo Object Type has a geometry type of POINT which is no longer an option supported.

**Comment by justinlewis** [comment]
Relates to [#353](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/353)

**Comment by justinlewis** [comment]
@steeveebener I think we should add this to the list of data changes needed for the new hierarchy functionality (e.g. grouping).

**Comment by SteeveEbener** [comment]
Thanks Justin. I guess this means that I will have to re-create the full Tolkien data once ve 13 has been released....

Closing this ticket in the meantime
