### ISSUE TITLE
Long hierarchy names are truncated on hierarchy header nodes

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#498]
![image (34).png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/ca963d29-90f5-4c4e-ac50-4c1332d9e780)

**Comment by rrowlands** [comment]
What is the desired solution here? Text wrapping I assume?

**Comment by justinlewis** [comment]
Wrapping is ideal

**Comment by rrowlands** [comment]
It was discussed on a phone call that the solution to this ticket is:

1. Do not do any text wrapping. This is because the header is too small to add an additional line. The header size must be increased, which then requires reworking all the hierarchy UI.
2. Add an elipsis to the label when it cuts to indicate that the label is truncated
3. Add a tooltip modal which appears when hovering over the node which displays the following information:
  a. Hierarchy label
  b. Hierarchy code
  c. Organization label

**Comment by rrowlands** [comment]
The new functionality can be seen in this screenshot.

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/f8c847a1-6b23-465a-bc3e-1c2bdcf435d9)

**Comment by SteeveEbener** [comment]
Tested under 0.13.1 (staging) and working but now it is the text of the overall hierarchy that see its lowest part truncated:
![Uploading image.png…]()

**Comment by rrowlands** [comment]
Hi Steve. It looks like something happened which has prevented your screenshot from uploading properly. Can you try reuploading your screenshot?

**Comment by SteeveEbener** [comment]
Hi Richard. Sorry for not seeing this. Screenshot re-uploaded
