### ISSUE TITLE
Disparate List Mapping Tool v1

### ISSUE THREAD

**Issue by steesdale** [terraframe/geoprism-registry#52]
Provide a tool that will map the IDs of a master list with the corresponding IDs of the same geographies from another list.

Epic documentation and user stories: [Shared Google Doc](https://docs.google.com/document/d/1497lnKCBSdOelpaiCsJXR1h17gSsap_PIdRo6T2Fy5U/edit#)

This is being broken down into two tasks to represent that common core functionality has been identified between other use cases. Version 1 of this requirement will focus on building the UI infrastructure that will be adapted for asynchronous use in the spreadsheet and shapefile importers, which currently are synchronous tasks that will be converted to asynchronous tasks. Synchronizing disparate lists between different systems would be an asynchronous process given the size of the lists. A job scheduler will be developed that summarizes the status, success, and list failures of data import tasks.Users will be able to address these failures and reprocess the task.

**Comment by dtreatman** [comment]
Questions:

- Should the CGR store the output of this feature (e.g., lists of linked unique IDs from different systems)? I would say it should.

**Comment by SteeveEbener** [comment]
Two comments:
1. The matching functionality is not core to the CGR concept but more a tool that will help users to align the list(s) contained in their information system with those stored in the CGR => This is a tool that should be part of the Geoprism toolbox and not part of the CGR, which answers Derek's last question
2. Using geographic coordinates as the only information to proceed with the matching is a very dangerous practice that should not be considered and this simply due to the general level of uncertainty attached to any set of geographic coordinates. What we have been discussed with TF is to measure the level of matching across all the CGR type information (uniquely ID, classify, locate and, when it applies contact) stored in both lists and provide such measure to the user for him to decide if the matching should be performed or not

**Comment by SteeveEbener** [comment]
Still using "mapping" for a functionality that does not relate to geographic mapping in a tools dealing with geographic information :)
