### ISSUE TITLE
Add new Geo-Object option not appearing in all lists

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#589]
**List the CGR information**
- CGR version: 0.14.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**

**To Reproduce**
1. See @peedropagalday's comment below

**Expected behavior (clear and concise)**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by PedroPagalday** [comment]
@justinlewis this are the steps to reproduce

- As a registry administration for the MOH organization, I have created a multiple Geo-Object Type groups, with several Geo-Objects.
- All the Geo-Object Types are set as "Public"
- I upload data for all the Geo-Object Types and create the lists as public
- Open the list module, create an exploratory list for the date = today
- The button "Add Geo-Object" only shows in some Geo-Object Types list randomely.

Expected behavior: RAs and RMs are able to add Geo-Objects to the Lists that they have under their mandate

**Comment by rrowlands** [comment]
![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/24337da7-4760-4e4d-9166-98f7d964a263)

**Comment by SteeveEbener** [comment]
We need to discuss terminology here because technically "health facilities" in this case is a group (that's the way we define it when creating it in the geo-object types and hierarchies module) and not a geo-object type => we can't talk about "Sub-type".

=> If we follow what we have been implementing so far, it should read "Select a geo-object type". A bit long but correct
