### ISSUE TITLE
When viewing a geo-object in explorer view, attribute information is missing

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#613]
**List the CGR information**
- CGR version: v14.5
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When comparing a geo-object in explorer view vs. list view the explorer view is missing data for the geo-object

**To Reproduce**
1. As a RC: Go to the explorer view
2. Search for Abella I Health Post
3. Click on the health post
4. See error: Data missing for all attributes apart from geo-object unique ID

**Expected behavior (clear and concise)**
Attribute information in the explorer view should be displayed in a similar manner when accessing the geo-object from list view.

**Screenshots**
Explorer view
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/223ab6be-cbd4-44ea-b40e-f76fbe04def9)

List view
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/c7bda370-f5da-47ff-bf35-c17cc4d2c04b)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser: Google Chrome
 - Version: latest

**Additional context (if any)**

**Comment by jsmethie** [comment]
In the explorer view you need to select a date.  From your screenshot there is no date selected, which means it is there are not attribute entries to display at that time.

**Comment by vrajasekaran18** [comment]
Hey @jsmethie thanks for getting back to me! Follow-up on two things:
1) I also saw this behaviour (of missing attribute data) from the change request module, where the RC searches for the geo-object selects to edit it and then they don't see attribute data.

2) In previous versions you didn't need to select a date in the explorer module when searching and clicking geo-objects, the system (I'm guessing) would pick today and show the attribute values as for today? What made the team decide to change the behaviour?

**Comment by rrowlands** [comment]
Hi Varshana. @jsmethie is needed on another project so I will be assisting with this ticket.

There has been confusion around this use-case for quite some time so I see some value in clarifying.

1. I have modified this use-case to require the user to input a date before opening the Geo-Object editor (see screenshot below). This date will also be used when clicking the "show details button".

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/ec421190-6485-48a5-b93f-fee2947e1a26)

2. To my knowledge this wasn't an intentional change, my guess is this happened accidentally. Since we've had quite a bit of confusion around this use-case, I have added an error message which should notify the user that they need to select a date, and should explain a little bit as to why. You can see the error message displayed to the user if they attempt to select a Geo-Object without selecting a date:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/49dcfa67-4fd0-47e6-a6ea-fdddc3276137)

**Comment by rrowlands** [comment]
> For the change request module, in the past (so I guess v12 and before), an RC could submit a change request from the change request module. Was there a need for the RC to select a date?

I believe in this scenario we did not allow the user to set a date here, however there was always an 'implicit' (secret) date which was set to today's date. Having a secret date which the user is completely unaware of is also confusing.

> Could the system not just select today's date as the date selection doesn't change the attributes/instances they will view in the editing window.

The submit change request module has the ability to view the attributes on the Geo-Object (via the "show details" button). Prior to my changes in this ticket, this date was secretly set to today's date, which again I argue is confusing since the user cannot change it and has no idea that it is being used. This date is used when showing attributes to the user, i.e. display label. The display label must be resolved to a date since it is a change-over-time attribute.

> Also in the hopes of simplifying things, is there a reason we go to the explorer view to edit the geo-object rather than the view an RC gets when editing a geo-object from the list view? Because to be fair, the explorer view when editing a geo-object from the change request module can be confusing because of the date, search input and back to results UI that a user can't or gets blank results when they interact with. (Sorry! I may be opening a can of worms).

Hmm... this is a good point. Let me see what I can do.

**Comment by rrowlands** [comment]
Regarding your last point, I can't use the dataset explorer to view the object because it's not associated with a list and that viewer only works for list data. That being said, I have made an effort to disable those confusing search options for this usecase.

**Comment by SteeveEbener** [comment]
I think that this is a perfect illustration of the limited added value that the current version of the Explorer brings to the CGR platform.

This module really serves only one use case which, according to me, has no real value in view of what can already be done in the lists module.

In addition to that, the fact that you can view in the explorer any data coming from lists that are actually private is in direct contradiction with the rules currently implemented in that same lists module.

**Comment by SteeveEbener** [comment]
Coming back to the original issue posted by Varshana, the issue also happens when looking at a geo-object in the geo-object modal in the lists module. Screenshot from my side taken from the Demo instance today:

Inactive Shire:
 
![image](https://user-images.githubusercontent.com/12602163/116782545-531e4b80-aabc-11eb-8e17-7d0ff46029bb.png)

Active village: 

![image](https://user-images.githubusercontent.com/12602163/116782548-5d404a00-aabc-11eb-994d-f23bb346de56.png)

**Comment by rrowlands** [comment]
The final outstanding concern in this ticket is now superseded by #633. In an effort to reduce operational burden on our team I am closing this ticket.
