### ISSUE TITLE
Set representativity date and publish date in master list automatically

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#63]
The "Representativity Date" and "Publish date" field should not be manual but generated automatically by the system based on the time stamps stored in the backend.

**Comment by SteeveEbener** [comment]
Further thinking on this issue, including the way the COT are being integrated in the platform, what should actually happen in the metadata window of a master list is as follow:

1. The publish date should be removed because this is specific to each "extraction"
2. The representativity date should:

- Either be removed as well because also related to a specific “extraction”
- Or replaced by two fields that would indicate for which period of validity there is information in the graph for this particular GeoObject type (start and end date)
