### ISSUE TITLE
RC can't see the Historical Events module

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#686]
**List the CGR information**
- CGR version: 0.17.0
- CGR instance (e.g. a URL): staging/demo

**Describe the bug (clear and concise)**
The Historical Events module is not available to the RC role

**To Reproduce**
As RC:
1. Log in
2. See error: the module is not there (Screenshot below)

**Expected behavior (clear and concise)**
The historical events module is accessible to the RC in the view mode only

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/141109328-f1027c0c-156b-4561-86f3-70de4bdcc40c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
Perhaps we should make certain that we are on the same page with regards to expected permissions for this module.

We have the following actions:
1. READ existing data.
2. WRITE, or update existing transition events
3. DELETE existing transition events
4. CREATE new transition events
5. VIEW_REPORTS

We also have two different GeoObjectTypes that permissions can be checked against, since transition events are associated with a before type and an after type.

**Comment by SteeveEbener** [comment]
Tested under 0.19.5 and the module is now visible to the RCs => closing this ticket
