### ISSUE TITLE
Historical Events: the description field should not be mandatory

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#691]
**List the CGR information**
- CGR version: 0.17.0
- CGR instance (e.g. a URL): Staging/demo

**Describe the bug (clear and concise)**
The RA/RM has to enter a description for the event to be able to submit it

**To Reproduce**
As a RA/RM (for Moha for example):
1. Go to Historical Events module
2. Create a new event 
3. Try to submit the event without entering a description
4. See error: you can't submit the event

**Expected behavior (clear and concise)**
There is not need to enter a description for the event to be able to submit it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Thanks for the clarification.

What if the person does not speak English and can only enter a description in the local language?

I think that a better approach here would then be to: 1. Not make this field mandatory; 2. Display the description in the local language in the home page as well.

Apart from that, I don't think that using the description in the messages like the one you presented is a good  practice (could be very long, not very information, not informative if the person does not speak English and not unique)=>  I would use the Event Id for the types of messages you are mentioning. This one is unique, not reused (right?) and independent from language

P.S. Thanks for using historical events and not transition event to avoid confusion

**Comment by rrowlands** [comment]
I can sympathize with your point, however now I would argue that your argument, if valid, also applies to Geo-Objects and Geo-Object Types. The default locale is mandatory for creation of both of those objects.

**Comment by justinlewis** [comment]
Rich and I talked about this offline. We think you're #1 makes sense. We where trying to use desciption as a way for someone to see at least something about the transition before deleting it because we don't have a label. Sort of a last chance to get some context on what you're deleting before deleting it. I don't think ID will really be that useful because they are unlikely to know the ID of the transition they're deleting but in this use case they actually clicked that transition (as long as they didn't miss) so they don't really need to know the ID in this context. That said we can add it like you're asking just in case and remove the required property on description.

This means the message would be "Are you sure you want to delete [id of transition]?

Regarding your #2, what do you mean by "home page"?  Right now the description field is localized. 

input view:
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/f1034e3b-1f28-4237-a6a4-e5dda6d4169a)

default locale view:
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/711f357c-8b0c-401c-bf90-3aa6d24d778f)

laos locale view:
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/ca6e4118-b9ff-4c04-a603-806c2589ca32)

**Comment by SteeveEbener** [comment]
Thanks Justin. Looking forward to the implementation of the modification

**Comment by SteeveEbener** [comment]
Tested under 0.17.2 and working. I am closing this ticket
