### ISSUE TITLE
Additional locales are required in change request submission 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#74]
The change request window makes it mandatory to enter the name of the GeoObject in the different local while they were not mandatory at that time

**Comment by dtreatman** [comment]
Agree on prioritizing this fix

**Comment by justinlewis** [comment]
This was fixed with: https://github.com/terraframe/geoprism-registry/pull/290

**Comment by SteeveEbener** [comment]
This issue is linked to the need for the RA to specify if an attribute is mandatory for creating a new GeoObject type or not in the GeoObject type and hierarchies module.

This field used to be there but has been removed. 

This issue as well as related ones are reported in ticket #299 and remains to be addressed
