### ISSUE TITLE
Frequency-based lists created for the day before the specified start date and the first instance is not created

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#788]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): Demo/staging

**Describe the bug (clear and concise)**
1. When creating a frequency-based set the instances are created for the day before the start date and not the start date itself.
2. The first instance should correspond to the start date is not created

Example: when setting the start date to be 2000-01-01 on an annual frequency the instances should be created for:
2000-01-01
2001-01-01
...

The instances that are currently being created are:
2000-12-31 
2001-12-31
2002-12-31
....

**To Reproduce**
As a RA/RM:
1. Go to the lists/spatial data module
3. Create a new frequency-based set for a geo-object type under your curation mandate  starting on 2000-01-01 (annual frequency for example but the problem is the same across frequencies)  
4. Open the set and see the errors. The instances that have been created are for  2000-12-31, 2001-12-31, .... while they should have been created fro 2000-01-01, 2001-01-01, 2002-01-01

**Expected behavior (clear and concise)**
- The first instances is created for the frequency start date
- The following instances are created for the correct date and not the day before

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**
This is an old bug that is re-appearing

**Comment by jsmethie** [comment]
Duplicate of 265

https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/265

**Comment by SteeveEbener** [comment]
The ticket in which the issue regarding the date for which the list was appearing the day before in the previous design is indeed ticket #265 (starting from comment dated Mar 27, 2021).

To summaries, what we are now referring to as being a "frequency-based set" is what we used to called a "published list" in the previous design => the beahivor regarding the creation of the instances should remain the same
 
Note: it remains correct to create a new ticket (#788 and not re-open #265 because the latter is related to the previous design

**Comment by justinlewis** [comment]
@steeveebener We verified in the history of the source code that the logic for what date is used for the frequency periods is the exact same between the old published list behavior and the new series. In both cases the logic uses the start data to generate each interval for calendar periods starting on the 1st of the year. I think ticket #265 articulates your ask to change this so that the extraction date is the exact date entered by the user instead of the current behavior. 

Because the title of ticket #256 is clear and the conversation in that ticket outlines the details I agree we should open it back up. I'll do that. 

However, I agree with @jsmethie that this ticket is effectively a duplicate of that ticket because what's causing the issues you're reporting in this ticket is a result of the current logic. The cause of what you're describing here was outlined by @rrowlands in [this comment](https://github.com/terraframe/geoprism-registry/issues/265#issuecomment-944518532). The important thing to note is that the first list in your example:

> Open the set and see the errors. The instances that have been created are for 2000-12-31, 2001-12-31, .... while they should have been created fro 2000-01-01, 2001-01-01, 2002-01-01

is not extracted on the day before. They're the last day of an annual frequency starting now earlier than the start date entered by the user and based on calendar periods starting from the 1st day of the year. I think what's confusing is that your example uses January 1st. If you change that to something like May 15 the lists would still be 2000-12-31... Again, I understand this is not the behavior you want implemented. #265 outlines the behavior you want to see implemented. If #265 implemented what you're reporting here would not be occurring. This is why we see this as a duplicate. 

That said, if you want to keep it open we can but we'll treat #265 as the fix for this ticket and they both will be addressed at the same time because ultimately they both require changing the behavior of setting frequency periods. 

The next steps are to prioritize #265 and determine how it fits in the roadmap.

**Comment by SteeveEbener** [comment]
Hi @justinlewis . Thanks for the explanation. No problem to let both tickets open if this can help you.

The only thing though is that these instances should not be referred to as frequency "periods". These are not periods but single date instance of the graph generated starting from a specific date and at a given frequency.  

=> the temporal validity of these single date instances should be of the type "valide on (date)"  and NOT "valid for (period)"

**Comment by rfromthecastle** [comment]
Working when following the steps to reproduce, in v0.19.5 on Staging.

**Comment by SteeveEbener** [comment]
Confirmed as working under 0.19.5. Closing this ticket.
