### ISSUE TITLE
Format in which you can export an extracted master list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#83]
The fact that you can export a master list into a shapefile from the master list manager is confusing. 

We should only be able to export into a shape file from the "geospatial data manager" module especially as the system does not currently allow you to know if a shape file presenting the geography matching the list is available

**Comment by justinlewis** [comment]
This ticket depends on the Geospatial Data Manager epic and should be considered in that planning process.

**Comment by CarlyNel** [comment]
Justin: This can’t be estimated because there is a prerequisite requirement of having a geospatial data manager. To simply move the export functionality to a different widget (if it existed) is 5 - 8 story points.

Anne confirmed that this will remain in the backlog until a decision has been made on the geospatial data manager.

**Comment by SteeveEbener** [comment]
This issue has been addressed with the new design => I am closing this ticket
