### ISSUE TITLE
Support to store images

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#890]
## User stories
As a Registry Maintainer, I would like to be able to store images for Geo-Objects, for example a picture of a health facility, so that it is easier to identify the Geo-Object on the ground.

## Problems this relates to
Data management

## Proposed solution
Support 'image' data type for attributes

## Considered alternatives
Store URL to photo in text field

## Additional context
Many online facility registries in other countries have photos for each health facility.

**Comment by SteeveEbener** [comment]
Giving the possibility to store images would require the management of these images including the possibility to submit them for approval as part of a change request.

The easiest solution, and the one we should consider at this stage, is to create a text field in which the URL would be stored (an alternative solution proposed by Rica).

This issue is linked to ticket #209

**Comment by rfromthecastle** [comment]
Closing this ticket as the alternative solution proposed (using links to refer to images) is sufficient
