### ISSUE TITLE
DHIS2 synchronization support for v2.40

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#897]
## User stories
As a Registry Administrator, I would like to be able to synchronize Geo-Objects with organization units in the latest upcoming version of DHIS2, v2.40, which will be released in April 2023.

## Problems this relates to
Interoperability

## Proposed solution
Test DHIS2 synchronization with v2.40

## Considered alternatives
None

## Additional context
The Lao MoH will be upgrading their HMIS to DHIS2 v2.40 in Q2 2023.

**Comment by rrowlands** [comment]
Tests are currently passing against

https://play.dhis2.org/2.40dev

so it appears the systems are currently compatible. I'll wait until 2.40 is actually released and then do a final test and rubber stamp it. Any idea when 2.40's release is targeted?

**Comment by rfromthecastle** [comment]
Hi @rrowlands, the release of DHIS2 v2.40 is targeted for April 2023 according to their roadmap, and the upgrade of the Laos HMIS to this version will be sometime in Q2 2023.

**Comment by rrowlands** [comment]
OK I have tested their released v2.40.0. Apparently they decided to release this as v40.0.0? This seems like a white labeling though because their "system info" api endpoint returns the version as 2.40.0. We'll need to keep an eye on this, if their system info changes the way their versioning works it could definitely cause incompatibilities with our integration.
