### ISSUE TITLE
Error message details empty for external system synchronization

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#909]
**List the CGR information**
- CGR version: 1.2.1
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
The error message details are empty when an external system synchronization fails.

**To Reproduce**
1. As a Registry Administrator, run a synchronization that causes an error.
2. Click on details.
3. The table with error details is empty.

**Expected behavior (clear and concise)**
Details of the error are provided.

**Screenshots**
![image](https://github.com/terraframe/geoprism-registry/assets/18660080/0ebd7999-216e-4cf9-b2df-074dc324e75f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 114.0.5735.134

**Additional context (if any)**

**Comment by rrowlands** [comment]
Looks like the root cause here is the same corrupt data in the DHIS2 database, first discovered here:
https://github.com/terraframe/geoprism-registry/issues/898#issuecomment-1507467413

If this was working in the past, it could be because the updated DHIS2 software is doing better validation of the translations (but hasn't patched out the existing corrupt data).

The following request:
https://dhis2.asia/laohmis/api/metadata.json?organisationUnits=true&filter=id:eq:HTCt5PAPTQN

Reveals that there is an existing "description" translation without any locale:
```
{
  "property": "DESCRIPTION",
  "value": "ສຮສກ (ສາງໂຮງໝໍສູນກາງ)"
},
```

When our system attempts to submit changes to unrelated data, the DHIS2 notices the existing corrupt data and throws an error.

I will do the following:
1. Improve our sync page so that it doesn't glitch out as described in this ticket
2. Clean up the data as it passes through our system so that DHIS2 won't reject it when it comes back in.

**Comment by rfromthecastle** [comment]
Having difficulty replicating the bug on Staging and re-testing, so will only be able to test and confirm the fix is working once deployed to the Laos instance.

**Comment by rfromthecastle** [comment]
Working on the Laos instance. Thanks for fixing!
