### ISSUE TITLE
Need to capture more information for each user

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#97]
We should add more fields to capture the function and full contact information of any user as this will for example be used for the update request manager.

Here is the list of proposed fields (some of them are already included):
- Full name (English)*
- Full name (local)
- Organization*
- Country
- Position/Function*
- Phone number 1*
- Phone number 2
- Email address*
- Role*

I have added a * next to the fields which I think should be mandatory

**Comment by dtreatman** [comment]
Agree, but suggest a minor modification: "Title"  instead of "Position/Function", which should follow Organization. Updated list below. Also, want to confirm with Steeve that by "Role", he meant "System role"  for the CGR (which exists already)

- Full name (English)*
- Full name (local)
- Organization*
- **Title***
- Country
- Phone number 1*
- Phone number 2
- Email address*
- **System** role*

**Comment by SteeveEbener** [comment]
Yes, role was referring to the role in the CGR (RM, RC,...

**Comment by SteeveEbener** [comment]
This issue has partially been addressed as part of release 0.7.0.

The fields that remains to be added are:
 - First name (local)
 - Last name (local)
 - Organization*
 - Title*
 - Phone number 2

Field listed previously which might not be necessary anymore:
 - Country

**Comment by justinlewis** [comment]
We are going to implement the fields mentioned in the last comment except for Country. 
- First name (local)
- Last name (local)
- Organization*
- Title*
- Phone number 2

I agree with @dtreatman that we should use "Position/Function" instead of Title. @steeveebener - Do you agree?

**Comment by justinlewis** [comment]
@steevebener - I don't understand why Organization is needed because that is set through the existing roles assignment process. Do we really need another Organization field? It seems like the most we should do here is display this as read only based on what roles the user is assigned to. But really that is redundant because you can look at the role assignment of the user to determine this.

**Comment by SteeveEbener** [comment]
@justinlewis : 

1. Agree on using position/function instead of title as proposed by Derek

2. Organization here was not meant in the sense of the "CGR organization" as such concept was not exciting by then but in the sense of capturing where the user sits physically => Maybe that we should convert this into Department/division/Unit

This being said, there is at least one case where the "CGR organization" should be displayed and this is when the SRA will look at all the RA accounts => without this information he will not be able to know to which organization each RA is attached to.

Going through this question made me also wonder if the RA of organization A should not see the RA for the other organizations but maybe that such contact should happen through the organization.

=> This made me realize that I did not yet submit a ticket to also expand the list of fields for the Organization contact details (only captured in my feedback google doc for the moment). I have captured that in ticket #288 in case you would like to address this at the same time

**Comment by justinlewis** [comment]
Ok. So it sounds like we should add:

- First name (local)
- Last name (local)
- Department*  ---> if a certain country doesn't call this Department we can use localization to change it to something like Division
- Title*
- Phone number 2

The SRA would know which organization an RA is attached to by looking at the roles unless this is a brand new user in the system who hasn't been assigned anything... In that case the SRA wouldn't be looking at RA's specifically they would be looking at users to assign them as an RA to an organization. If we think that this specific use case might be common we can add an optional "Organization" field however this adds another field to be managed while in reality the roles settings would be more reliable. My opinion is to leave this field out. The "Department" field will be free text so the user could always setup that field like:
- "MOH - Failities Department - Analyst"

**Comment by SteeveEbener** [comment]
1. yes expect that it should be "Position/Function" instead of "Title"

2. As per the rights by role spreadsheet, the SRA will only see and manage the RA accounts across  all the organizations  => only RAs will appear in the user account table under settings (first screenshot below for reference). 

=> what will be the content of the "role" field in this table?  "Registry Administrator" only or "Ministry of Education Registry Administrator" like it is currently appearing when opening the detailed window? (second screenshot below). 

If the latter then we are all good. If the former then I still think we need a way for the SRA to know about the RA organization directly in the user account table as the list might become long quickly.

![image](https://user-images.githubusercontent.com/12602163/84449890-4369fe80-ac81-11ea-831f-3eefa80369f0.png)

![image](https://user-images.githubusercontent.com/12602163/84450570-19b1d700-ac83-11ea-9129-6b1514025694.png)

**Comment by justinlewis** [comment]
@steeveebener If I understand correctly adding a roles column to the users table and populating it with the full role names (e.g. Ministry of Education Registry Administrator) will satisfy the use case where an SRA wants to see all the RA's in the system while clearly seeing which Organization they belong to.

Another option is to add anOrganization column to the roles table so we can see the role and org side by side. This might be a more consistent layout because it would allow us to have a more consise list of roles for RM and RC roles when an RA looks at the table. This isn't a critical need but want to present it as an option.

**Comment by SteeveEbener** [comment]
@justinlewis : yes, you got it right and I would also be in favor of the second option

**Comment by justinlewis** [comment]
I created a [new ticket for the additional changes to the user table](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/295). 

We're modifying the user profile form like outlined in my comment above to add:

- First name (local)
- Last name (local)
- Department* ---> if a certain country doesn't call this Department we can use localization to change it to something like Division
- Position/Function*
- Phone number 2

**Comment by SteeveEbener** [comment]
Could we just make the size of the field for the email address bigger? This ticket can be closed after that

**Comment by jsmethie** [comment]
Please create a new ticket to change the size of an email field
